[tool.poetry]
name = "QuoteBotRepo"
version = "1.2.0"
description = "A repository for the QOTD bot on the swan_hack Discord server"
authors = ["Gnomeball", "AlexBlandin", "KrisRalph", "dedbepole"]

[tool.poetry.dependencies]
python = "^3.7"
"discord.py" = "^1.7.3"
tomli = "^1.2.1"
tomli_w = "^0.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
