[tool.poetry]
name = "QuoteBotRepo"
version = "1.2.0"
description = "A repository for the QOTD bot on the swan_hack Discord server"
authors = ["Gnomeball", "AlexBlandin", "KrisRalph", "dedbepole"]

[tool.poetry.dependencies]
python = "^3.8"
py-cord = "^2.0.0"
tomli = "^2.0.1"
tomli_w = "^1.0.0"
requests = "^2.27.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
